// src/main.js — App entry point
import { state } from './engine/game-state.js';
import { TurnManager } from './engine/turn-manager.js';
import { Renderer } from './ui/renderer.js';
import { loadCity } from './utils/validators.js';

// Import city data (will be generated by AI workers)
import jakartaData from './data/cities/jakarta.json';

class App {
  constructor() {
    this.state = state;
    this.turnManager = new TurnManager(this.state);
    this.renderer = new Renderer(document.getElementById('app'));
    this.currentScreen = 'dispatch';
  }

  async init() {
    // Load Jakarta as default city
    const city = loadCity(jakartaData);
    this.state.loadCity(city);

    // Render initial screen
    this.render();

    console.log('GOVERNED initialized. City:', this.state.city.city_name);
    console.log('Turn:', this.state.turn, 'Approval:', this.state.approval);
  }

  render() {
    this.renderer.render(this.currentScreen, this.state);
  }

  // Called by UI when player makes a decision
  handleDecision(decisionId, optionIndex) {
    this.turnManager.resolveDecision(decisionId, optionIndex);
    this.render();
  }

  // Called by UI when player clicks next turn
  nextTurn() {
    this.turnManager.processTurn();
    this.render();
  }

  // Called by UI when player clicks an advisor
  openMessenger(advisorId) {
    this.currentScreen = 'messenger';
    this.renderer.setActiveAdvisor(advisorId);
    this.render();
  }

  // Called by UI when crisis triggers
  openCrisis(crisisId) {
    this.currentScreen = 'crisis';
    this.renderer.setActiveCrisis(crisisId);
    this.render();
  }

  // Called by UI when term ends
  openReport() {
    this.currentScreen = 'report';
    this.render();
  }
}

// Start the app
const app = new App();
app.init();

// Expose for debugging
window.GOVERNED = app;
